### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jirutka** [sapo/nginx-log-zmq#22]
According to the readme, this module is production ready. If so, can you please create a release – tag a version?

**Comment by carlosefr** [comment]
To manage your expectations, I don't believe this is being maintained anymore, at least publicly.

**Comment by danifbento** [comment]
Hello @jirutka. I'm actually putting my hands again on this project: https://github.com/danifbento/nginx-log-zmq. 
I want to add some more features as soon as possible and I'm trying to verify if nothing is broken with recent nginx updates.

**Comment by jirutka** [comment]
Great! I’ve added https://github.com/danifbento/nginx-log-zmq to the nginx package in Alpine Linux.

**Comment by danifbento** [comment]
@jirutka Thanks! 👍
